# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .Net MAUI APP (CLI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on:  windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install .NET MAUI
      run : dotnet workload install maui
    - name: Restore DoToo
      run: dotnet restore DoToo/DoToo.csproj
    - name: Restore News
      run: dotnet restore News/News.csproj
    - name: Build DoToo and News projects
      run: |
        dotnet build DoToo/DoToo.csproj -c Release -f net9.0-android --no-restore
        dotnet build News/News.csproj -c Release -f net9.0-android --no-restore
